OldUI/TradeRiser/Controllers/MembershipController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TradeRiser.Core.Logging;
using TradeRiser.Core.SignOn;
using TradeRiser.Core.Membership;
using TradeRiser.UI.Models;

namespace TradeRiser.UI.Controllers
{
  


        ///// <summary>
        /////     The location group controller.
        ///// </summary>
        //[AuthorisedPermission("membership.app")]
        //[RouteArea("cpf")]
        //[Route("membership/{action=index}")]
        public class MembershipController : CpfController
        {
            /// <summary>
            ///     The sender.
            /// </summary>
            private const string SENDER = "MembershipController";

            #region  Fields

            /// <summary>
            ///     Location group service.
            /// </summary>
            private IMembershipService membershipService;


            private UserSignOnService signOnService;

            #endregion

            #region  Properties and Indexers

            public UserSignOnService SignOnService
            {
                get
                {
                    if (this.signOnService == null)
                    {
                        this.signOnService = new UserSignOnService(this.Director.Configuration);
                    }

                    return this.signOnService;
                }
            }

            /// <summary>
            ///     Gets or sets the membership service.
            /// </summary>
            /// <value>
            ///     The membership service.
            /// </value>
            public IMembershipService MembershipService
            {
                get
                {
                    if (this.membershipService == null)
                    {
                        this.membershipService = new MembershipService(this.Director.Configuration);
                    }

                    return this.membershipService;
                }

                set
                {
                    this.membershipService = value;
                }
            }



            #endregion

            #region  Public Methods

            /// <summary>
            ///     Edits the specified user.
            /// </summary>
            /// <param name="userName">Name of the user.</param>
            /// <param name="pageView">The Page view</param>
            /// <returns>
            ///     Edit view.
            /// </returns>
            // [Route("membership/edit/{userName}")]
            public ActionResult Edit(string userName, string pageView = null)
            {
                User user = this.MembershipService.GetUserByUserName(userName);
                SaveUserModel model = new SaveUserModel(user, null);
                //this.ViewBag.Languages = this.Languages;
                this.ViewBag.Languages = new Dictionary<string, string> { { "en-GB", "en-GB" }, { "en-US", "en-US" } };
                // page title
                this.ViewBag.HeaderTitle = string.Format("{0} > {1} {2}", TradeRiserUIResource.User, model.FirstName, model.LastName);
                this.ViewBag.PageView = pageView;
                return this.View("~/views/membership/Edit.cshtml", model);
            }

            /// <summary>
            ///     Indexes this instance.
            /// </summary>
            /// <returns>List of location groups.</returns>
            public ActionResult Index()
            {
                // return this.RedirectToAction("Index", "Search", new { area = "icms" });
                UserModel model = new UserModel();
                model.Users = this.Director.Membership.GetAllUsers();
                return this.View(model);
            }

            /// <summary>
            ///     News this instance.
            /// </summary>
            /// <returns>Edit view.</returns>
            public ActionResult New()
            {
                SaveUserModel model = new SaveUserModel(null, null)
                {
                    IsNewUser = true
                };
                this.ViewBag.Languages = new Dictionary<string, string> { { "en-GB", "en-GB" }, { "en-US", "en-US" } };

                // default to the same as the current user
                model.TimeZone = this.Director.User.TimeZone;
                model.LanguageCode = this.Director.Configuration.GetConfigItem("Core.DefaultLanguage", "en-GB");

                return this.View("~/views/membership/Edit.cshtml", model);
            }

            /// <summary>
            ///     News this instance.
            /// </summary>
            /// <returns>Edit view.</returns>
            public ActionResult SignUp()
            {
                SaveUserModel model = new SaveUserModel(null, null)
                {
                    IsNewUser = true
                };
                this.ViewBag.Languages = new Dictionary<string, string> { { "en-GB", "en-GB" }, { "en-US", "en-US" } };

                // default to the same as the current user
                model.TimeZone = this.Director.User != null ? this.Director.User.TimeZone : "en-GB";
                model.LanguageCode = this.Director.Configuration.GetConfigItem("Core.DefaultLanguage", "en-GB");

                return this.View("~/views/membership/SignUp.cshtml", model);
            }
            /// <summary>
            ///     Removes the specified user ids.
            /// </summary>
            /// <param name="memberIds">The member ids.</param>
            /// <param name="memberUserNames">The member user names</param>
            /// <returns>
            ///     Alert message.
            /// </returns>
            [HttpPost]
            public ActionResult Remove(string memberIds, string memberUserNames)
            {
                ResultBag resultBag = null;

                try
                {
                    System.Collections.Generic.List<System.Guid> userIds = new System.Collections.Generic.List<System.Guid>();
                    System.Guid userId = System.Guid.Empty;

                    foreach (string userIdGuid in memberIds.Split(','))
                    {
                        if (System.Guid.TryParse(userIdGuid, out userId))
                        {
                            userIds.Add(userId);
                        }
                    }

                    bool hasRemoved = this.MembershipService.DeleteUser(userIds);
                    if (hasRemoved)
                    {
                        Log.Audit(CoreConstants.LogComponent, MembershipController.SENDER, string.Format("The user(s) {0} have been deleted.", string.IsNullOrEmpty(memberUserNames) ? memberIds : memberUserNames), this.Director.User.UserName, this.Director.User.UserDisplayName, this.Director.User.UserID);
                        //this.ClearCache(userIds, true);
                        //this.ClearCache(this.Director.User.UserID, true);

                        Alert alert = new Alert(TradeRiserUIResource.Membership_RemoveSuccess, AlertType.Success, false)
                        {
                            Delayed = true
                        };

                        resultBag = new ResultBag(alert, true, string.Empty)
                        {
                            RedirectUrl = "membership"
                        };
                    }
                    else
                    {
                        Log.Warning(CoreConstants.LogComponent, MembershipController.SENDER, string.Format("The attempt to delete user(s) {0} has failed.", string.IsNullOrEmpty(memberUserNames) ? memberIds : memberUserNames), this.Director.User.UserName, this.Director.User.UserDisplayName, this.Director.User.UserID);
                        resultBag = new ResultBag(new Alert(TradeRiserUIResource.Membership_RemoveFailed, AlertType.Error, false), false, string.Empty);
                    }
                }
                catch (System.Exception ex)
                {
                    Log.Exception(CoreConstants.LogComponent, MembershipController.SENDER, ex, this.Director.User.UserName, this.Director.User.UserDisplayName, this.Director.User.UserID);
                    resultBag = new ResultBag(new Alert(TradeRiserUIResource.Membership_RemoveFailed, AlertType.Error, false), false, ex.Message);
                }

                return new JsonActionResult(resultBag);
            }

            /// <summary>
            ///     Disables the specified user ids.
            /// </summary>
            /// <param name="memberIds">The member ids.</param>
            /// <param name="memberUserNames"></param>
            /// <returns>
            ///     Alert message.
            /// </returns>
            [HttpPost]
            public ActionResult Disable(string memberIds, string memberUserNames)
            {
                ResultBag resultBag = null;

                try
                {
                    List<string> userIds = memberIds.Split(',').ToList();
                    bool hasDisabled = this.MembershipService.DisableUsers(userIds);
                    if (hasDisabled)
                    {
                        List<Guid> userIdList = new List<Guid>();
                        Guid userId = Guid.Empty;

                        foreach (string userIdGuid in userIds)
                        {
                            if (Guid.TryParse(userIdGuid, out userId))
                            {
                                userIdList.Add(userId);
                            }
                        }

                        Log.Audit(CoreConstants.LogComponent, MembershipController.SENDER, string.Format("The user(s) {0} have been disabled.", string.IsNullOrEmpty(memberUserNames) ? memberIds : memberUserNames), this.Director.User.UserName, this.Director.User.UserDisplayName, this.Director.User.UserID);
                        //this.ClearCache(userIdList, true);

OldUI/TradeRiser/Views/Membership/Edit.cshtml
 @using TradeRiser.UI
@using TradeRiser.UI.Controls
@using TradeRiser.UI.Models
@{
    //this.ViewBag.Title = TradeRiserUIResource.Membership_Title;
    //this.ViewBag.SubNav = SecondaryNavigations.Normal;
    //this.ViewBag.ShowHeader = ShowHeader.Show;
    string t = string.Empty;
}
@model SaveUserModel
@section head
{
   
    <script type="text/javascript">
        $(function () {

            @if (this.ViewBag.Saved != null && !this.ViewBag.Saved)
            {
                <text>corejs.alert("@Html.Raw(this.ViewBag.Message)", "e")</text>
            }
        });

        PAGEVIEW = "@this.ViewBag.PageView";
    </script>
}
@section jQueryLoad
{
    members.edit.load();
}
@section scripts
{
}

@section ribbon
{
    <li class="nav-item"><a id="back-button" href="#" class="nav-link"><span class="fa fa-chevron-left"></span>@Html.Raw(TradeRiserUIResource.Ribbon_Membership_Cancel)</a></li>

    @if (this.Model.UserID != Guid.Empty || this.Model.IsNewUser)
    {
        <li class="nav-item"><a id="membership-button-save" href="#" class="nav-link"><span class="fa fa-fw fa-save"></span>@Html.Raw(TradeRiserUIResource.Ribbon_Membership_Save)</a></li>
    }

    @if (this.Model.UserID != Guid.Empty)
    {
        <li class="nav-item"><a id="membership-button-reset-password" href="#" class="nav-link"><span class="fa fa-fw fa-lock"></span>@Html.Raw(TradeRiserUIResource.Ribbon_Membership_ResetPassword)</a></li>
        <li class="nav-item"><a id="new-permission" class="nav-link" href="@Url.Content("~/core/permission/new?userOrGroupName=" + this.Model.UserName + "&userOrGroupID=" + this.Model.UserID)"><span class="button-icon fa">@Html.Raw(TradeRiserUIResource.Icon_Password)</span>@Html.Raw(TradeRiserUIResource.Create_Permission)</a></li>
        @*<li><a id="delete-permission" href="#"><span class="button-icon disabled">@Html.Raw(TradeRiserUIResource.Icon_Delete)</span><span class="button-label">@Html.Raw(TradeRiserUIResource.Delete_Permission)</span></a></li>*@
    }
}

@if (this.Model.UserID == Guid.Empty && !this.Model.IsNewUser)
{
    <h1>@TradeRiserUIResource.UserNotFound</h1>
}
else
{
    @*@section subnav
      {
        <ul id="membership-menu">
            <li><a id="membership-details" class="selected" href="#">@TradeRiserUIResource.Membership_Details_Title</a></li>
            <li><a id="membership-groups" href="#">@TradeRiserUIResource.Membership_Groups</a></li>
            <li><a id="membership-location-groups" href="#">@TradeRiserUIResource.Membership_Location_Groups</a></li>
           
            <li><a id="membership-preferences" href="#">@TradeRiserUIResource.Membership_User_Preferences</a></li>
        </ul>
    }
@*



    @:@section messagebox{
        @Html.Action("Message", "Core", new
   {
       area = "cpf",
       model = new TradeRiser.UI.Message()
       {
           Content = TradeRiserUIResource.ResetPasswordMemberText,
           ID = "reset-password-membership-confirmation",
           NoButtonText = TradeRiserUIResource.NoButton,
           Title = TradeRiserUIResource.ResetPassword_Title,
           YesButtonText = TradeRiserUIResource.YesButton,
           IconType = MessageIconType.Warning
       }
   })
        @Html.Action("Message", "Core", new
   {
       area = "cpf",
       model = new TradeRiser.UI.Message()
       {
           ID = "reset-password-membership-complete",
           SingleButton = true,
           Title = TradeRiserUIResource.ResetPassword_Title,
           IconType = MessageIconType.Success
       }
   })
    }*@




    <div class="membership-content">
        <div class="section" id="member-section">
            <div class="section-title">
                <div class="title-wrapper">
                    @TradeRiserUIResource.Membership_Details_Title
                </div>
            </div>
            <div id="member-details" class="section-content">
                <input type="hidden" id="userid" name="userid" value="@(!this.Model.IsNewUser ? this.Model.UserID.ToString() : string.Empty)" />
                <label for="first-name">@TradeRiserUIResource.Membership_FirstName @Html.ValidationControl("first-name", true)</label>
                <input type="text" id="first-name" name="first-name" maxlength="255" class="form-control cpftxt" value="@Model.FirstName" @Html.ValidationAttributes(new ValidationAttributes() { Required = true }) />
                <label for="last-name">@TradeRiserUIResource.Membership_LastName @Html.ValidationControl("last-name", true)</label>
                <input type="text" id="last-name" name="last-name" maxlength="255" class="form-control cpftxt" value="@Model.LastName" @Html.ValidationAttributes(new ValidationAttributes() { Required = true }) />
                @if (!this.Model.IsNewUser)
                {
                    <label for="username">@TradeRiserUIResource.Membership_UserName</label>
                    <input type="hidden" id="username" name="username" value="@(!this.Model.IsNewUser ? this.Model.UserName : string.Empty)" />
                    <label class="cpftxt">@Model.UserName</label>
                }
                else
                {
                    <label for="username">@TradeRiserUIResource.Membership_UserName @Html.ValidationControl("username", true)</label>
                    <input type="text" id="username" name="username" maxlength="255" class="form-control cpftxt"
                           @Html.ValidationAttributes(new ValidationAttributes() { Required = true }) />

                }
                <label for="email">@TradeRiserUIResource.Membership_Email @Html.ValidationControl("email", true)</label>
                <input type="text" id="email" name="email" maxlength="255" class="form-control cpftxt" value="@Model.Email" @Html.ValidationAttributes(new ValidationAttributes() { Required = true, Email = true }) />
                <label for="phone1">
                    @TradeRiserUIResource.Membership_Phone1
                </label>
            @*    <input type="text" id="phone1" name="phone1" value="@Model.Phone1" maxlength="255" class="cpftxt form-control" />
                <label for="phone2">
                    @TradeRiserUIResource.Membership_Phone2
                </label>*@
                <input type="text" id="phone2" name="phone2" value="@Model.Phone2" maxlength="255" class="cpftxt form-control" />
           @*        <label for="user-language">
                    @TradeRiserUIResource.Membership_Language @Html.ValidationControl("user-language", true)
                </label>
             <div class="select-wrapper">
                    <select id="user-language" name="user-language" @Html.ValidationAttributes(new ValidationAttributes() { Required = true })>
                        @foreach (KeyValuePair<string, string> language in @ViewBag.Languages)
                        {
                            <option value="@language.Key" label="@language.Value" @(language.Key == this.Model.LanguageCode ? "selected='selected'" : string.Empty)>@language.Value</option>
                        }
                    </select>
                </div>*@

                @if (!this.Model.IsNewUser)
                {
                    <label for="locked">
                        @TradeRiserUIResource.Membership_Locked

                        @if (this.Model.Locked)
                        {
                            <input id="locked" name="locked" type="checkbox" checked="checked" />
                        }
                        else
                        {
                            <input id="locked" name="locked" type="checkbox" disabled="disabled" />

                            <a tabindex="0" id="locked-help-link" class="help-link fa fa-question-circle bd-popover" role="button" data-dyno-type="help" data-toggle="popover" data-trigger="focus" title="Help" data-placement="bottom" data-content="@TradeRiserUIResource.Membership_LockedHelpText"></a>

                        }
                    </label>
                    <label for="disabled">
                        @TradeRiserUIResource.Membership_Disabled
                        <input id="disabled" name="disabled" type="checkbox" @(this.Model.Disabled ? "checked='checked'" : string.Empty) />
                    </label>
                }

           @*     <label for="employee-id">
                    @TradeRiserUIResource.Membership_EmployeeID
                </label>
                <input id="employee-id" name="employee-id" type="text" class="cpftxt form-control" value="@Model.EmployeeID" />*@

                
                   <label for="country">
                    Country
                </label>
                 <div class="select-wrapper">
                    <select id="country" name="country" @Html.ValidationAttributes(new ValidationAttributes() { Required = true })>
                        @foreach (string country in @Model.Countries)
                        {
                            string key = string.Empty;
                            if (this.Model.Country != null)
                            {
                                key = this.Model.Country.Trim();
                            }
                            <option value="@country" label="@country" @(country == key ? "selected='selected'" : string.Empty)>@country</option>
                        }
                    </select>
                </div>
                  <label for="broker-id">
                    Broker
                </label>
                <input id="broker-id" name="broker-id" type="text" class="cpftxt form-control" value="@Model.Broker" @Html.ValidationAttributes(new ValidationAttributes() { Required = true }) />

               @* <label for="primary-location-id">
                    @TradeRiserUIResource.Membership_PrimaryLocationID
                    @Html.Action("Help", "Controls", new
{
    area = "cpf",
    help = new HelpControl()
    {
        TargetID = "primary-location-id",
        Content = @TradeRiserUIResource.Membership_PrimaryLocationID_Help
    }
})
                </label>
                <input id="primary-location-id" name="primary-location-id" type="text" class="cpftxt form-control" value="@Model.PrimaryLocationID" />
           *@ </div>
        </div>
        <div id="user-group-permissions-wrapper" user-group-name="@this.Model.UserName" loaded="false">
        </div>
       @* @Html.Partial("~/core/views/Controls/Loader.cshtml")*@
    @*    <div id="user-groups-wrapper" style="display: none">
            @Html.Action("autocompletegrid", "controls", new
{
    area = "cpf",
    model = this.Model.UserGroupsGrid
})
        </div>
        <div id="user-location-groups-wrapper" style="display: none">
            @Html.Action("autocompletegrid", "controls", new
{
    area = "cpf",
    model = this.Model.UserLocationGroupsGrid
})
        </div>
        <div id="user-preferences-wrapper" style="display: none">
            @Html.Action("UserPreferences", "membership", new
{
    area = "cpf",
    UserId = !this.Model.IsNewUser ? this.Model.UserID : Guid.Empty
})
        </div>*@
    </div>
}

OldUI/TradeRiser/Views/Membership/Index.cshtml
@using TradeRiser.Core.Membership
@using TradeRiser.UI
@model TradeRiser.UI.Models.UserModel
@{
    //Layout = "~/Views/Shared/_LayoutPageNewTR.cshtml";
    //this.ViewBag.Title = TradeRiserUIResource.Account_Title;
    //TradeRiser.UI.TradeRiserUIResource
    int row = 0;                                 
}
@section jQueryLoad
{
    
}
    @section ribbon
{
       <li class="nav-item">
        <a href="@Url.Action("New", "Membership")" class="nav-link">
            <span class="fa fa-fw fa-plus-circle"></span>@Html.Raw(TradeRiserUIResource.Ribbon_Membership_NewGroup)
        </a>
    </li>
    @*<li class="nav-item">
        <a id="membership-button-edit" class="disabled nav-link" href="">
            <span class="fa fa-fw fa-pencil"></span>@Html.Raw(TradeRiserUIResource.Ribbon_Membership_EditGroup)
        </a>
    </li>
    <li class="nav-item">
        <a id="membership-button-delete" class="disabled nav-link" href="">
            <span class="fa fa-fw fa-trash-o"></span>@Html.Raw(TradeRiserUIResource.Ribbon_Membership_DeleteGroup)
        </a>
    </li>
    <li class="nav-item">
        <a id="membership-button-disable" class="disabled nav-link" href="">
            <span class="fa fa-fw fa-toggle-off"></span>@Html.Raw(TradeRiserUIResource.Ribbon_Membership_DisableGroup)
        </a>
    </li>
    <li class="nav-item">
        <a id="membership-button-enable" class="disabled nav-link" href="">
            <span class="fa fa-fw fa-toggle-on"></span>@Html.Raw(TradeRiserUIResource.Ribbon_Membership_EnableGroup)
        </a>
    </li>*@
         
    }
    @section subnav
{
        @*@{this.Html.RenderPartial("_UserMenu", "account");}*@
}

  <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Users <small></small>
                </h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">Settings 1</a>
                            </li>
                            <li><a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>

            <div class="x_content">

           @*     <p>Add class <code>bulk_action</code> to table for bulk actions options on row select
                </p>*@

                <div class="table-responsive">
                    <table class="table table-striped jambo_table bulk_action">
                        <thead>
                        <tr class="headings">
                            <th>
                                <div class="icheckbox_flat-green" style="position: relative;"><input type="checkbox" id="check-all" class="flat" style="position: absolute; opacity: 0;"><ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"></ins>
                                </div>
                            </th>
                            <th class="column-title">UserName </th>
                            <th class="column-title">First Name </th>
                            <th class="column-title">Last Name </th>
                            <th class="column-title">Email </th>
                            <th class="column-title">Last LogOn Date </th>
                            <th class="column-title">Locked </th>
                            <th class="column-title no-link last"><span class="nobr">Disabled</span>
                            </th>
                             <th class="column-title"> </th>
                           @* <th class="bulk-actions" colspan="7">
                                <a class="antoo" style="color: #fff; font-weight: 500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>*@                      
                        </tr>
                        </thead>

                        <tbody>                                              
                              @foreach (User user in this.Model.Users)
                              {
                                  row++;
                                  string rowClass;

                                    if (row % 2 == 0)
                                    {
                                        rowClass = "even";
                                    }
                                    else
                                    {
                                        rowClass = "odd";
                                    }  
                            <tr class="@rowClass pointer">
                                <td class="a-center ">
                                    <div class="icheckbox_flat-green" style="position: relative;"><input type="checkbox" class="flat" name="table_records" style="position: absolute; opacity: 0;"><ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"></ins>
                                    </div>
                                </td>
                            <td class=" ">@user.UserName</td>
                            <td class=" ">@user.FirstName</td>
                            <td class=" ">@user.LastName</td>
                            <td class=" ">@user.Email</td>
                            <td class=" ">@user.LastLogOnDate</td>
                            <td class=" ">@user.Locked</td>
                            <td class=" ">@user.Disabled</td>
                            <td class=" "><a href="~/membership/edit/@user.UserName">Edit</a></td>
                            </tr>
                        }                       
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@*<div class="settings-content page-content">
    <div class="section">
        <div class="section-title">
            <div class="title-wrapper">
            </div>
        </div>
    
        <div class="section-content" id="security-settings">
            <table>
                <thead>
                    <tr>
                        <th>UserName</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Email</th>
                        <th>Last LogOn Date</th>
                        <th>Locked</th>
                        <th>Disabled</th>
                    </tr>
                </thead>

                <tbody>
                   
                        @foreach (User user in this.Model.Users)
                        {
                        <tr>
                            <td>@user.UserName</td>
                            <td>@user.FirstName</td>
                            <td>@user.LastName</td>
                            <td>@user.Email</td>
                            <td>@user.LastLogOnDate</td>
                            <td>@user.Locked</td>
                            <td>@user.Disabled</td>
                             <td><a href="~/membership/edit/@user.UserName">Edit</a></td>
                        </tr>
                        }
                    
                </tbody>
            </table>
        </div>
    </div>
</div>*@